/**
 * Local artist → musical style mapping. Keys are normalized (lowercase, no accents).
 * Artist strings from user input must not be persisted or sent to third parties when
 * resolved locally; use the derived descriptors only downstream.
 */

export interface ArtistProfile {
  genres: string[];
  bpm_range: [number, number];
  energy: 'low' | 'medium' | 'high';
  density: 'sparse' | 'normal' | 'dense';
  mood_tags: string[];
  swing: boolean;
}

/** NFD strip combining marks */
export function normalizeArtistKey(input: string): string {
  return input
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .toLowerCase()
    .trim();
}

/** Build case- and accent-insensitive regex for a normalized ascii key */
function keyToFlexiblePattern(key: string): RegExp {
  const parts = key.split('').map((ch) => {
    if (/[a-z0-9]/.test(ch)) {
      return `${ch}\\p{M}*`;
    }
    if (ch === ' ') {
      return '\\s+';
    }
    return '\\' + ch;
  });
  return new RegExp(`(?:^|\\b|[^a-z0-9])(${parts.join('')})(?:$|\\b|[^a-z0-9])`, 'giu');
}

export function stripArtistKeyFromPrompt(prompt: string, matchedKey: string): string {
  const re = keyToFlexiblePattern(matchedKey);
  return prompt.replace(re, ' ').replace(/\s+/g, ' ').trim();
}

export function profileToDescriptorSuffix(p: ArtistProfile): string {
  const mood = p.mood_tags.join(' ');
  const genreLine = p.genres.join(' ');
  const swingBit = p.swing ? ' with swing' : '';
  return `${mood} ${genreLine}${swingBit}`.replace(/\s+/g, ' ').trim();
}

const BR: ArtistProfile = {
  genres: ['big room house', 'edm', 'festival'],
  bpm_range: [128, 135],
  energy: 'high',
  density: 'dense',
  mood_tags: ['anthem', 'euphoric', 'mainstage'],
  swing: false,
};

const TR: ArtistProfile = {
  genres: ['uplifting trance', 'progressive trance'],
  bpm_range: [136, 145],
  energy: 'high',
  density: 'normal',
  mood_tags: ['emotional', 'driving', 'euphoric'],
  swing: false,
};

const TH: ArtistProfile = {
  genres: ['tech house', 'groovy house'],
  bpm_range: [124, 132],
  energy: 'high',
  density: 'dense',
  mood_tags: ['groovy', 'driving', 'hypnotic'],
  swing: true,
};

const MH: ArtistProfile = {
  genres: ['melodic house', 'organic house'],
  bpm_range: [118, 128],
  energy: 'medium',
  density: 'normal',
  mood_tags: ['emotional', 'warm', 'progressive'],
  swing: false,
};

const AF: ArtistProfile = {
  genres: ['afro house', 'tribal house'],
  bpm_range: [120, 126],
  energy: 'high',
  density: 'normal',
  mood_tags: ['percussive', 'soulful', 'deep groove'],
  swing: true,
};

const MT: ArtistProfile = {
  genres: ['melodic techno', 'peak techno'],
  bpm_range: [130, 140],
  energy: 'medium',
  density: 'normal',
  mood_tags: ['hypnotic', 'dark', 'driving'],
  swing: false,
};

const MT_HARD: ArtistProfile = {
  genres: ['hard techno', 'industrial techno'],
  bpm_range: [140, 150],
  energy: 'high',
  density: 'dense',
  mood_tags: ['raw', 'distorted', 'relentless'],
  swing: false,
};

const DH: ArtistProfile = {
  genres: ['deep house', 'progressive house'],
  bpm_range: [118, 126],
  energy: 'low',
  density: 'sparse',
  mood_tags: ['warm', 'smooth', 'late night'],
  swing: false,
};

const DH_MED: ArtistProfile = {
  genres: ['deep house', 'nu disco'],
  bpm_range: [118, 126],
  energy: 'medium',
  density: 'sparse',
  mood_tags: ['groovy', 'soulful', 'bouncy'],
  swing: false,
};

const FB: ArtistProfile = {
  genres: ['future bass', 'electronic pop'],
  bpm_range: [90, 130],
  energy: 'high',
  density: 'dense',
  mood_tags: ['emotional', 'bright', 'anthemic'],
  swing: false,
};

const BS: ArtistProfile = {
  genres: ['dubstep', 'bass music', 'drum and bass crossover'],
  bpm_range: [140, 175],
  energy: 'high',
  density: 'dense',
  mood_tags: ['heavy', 'aggressive', 'wobble'],
  swing: false,
};

const CL_EDM: ArtistProfile = {
  genres: ['electronic', 'dance music'],
  bpm_range: [120, 135],
  energy: 'high',
  density: 'dense',
  mood_tags: ['classic', 'timeless', 'club'],
  swing: false,
};

const CL_TECH: ArtistProfile = {
  genres: ['detroit techno', 'minimal techno'],
  bpm_range: [128, 138],
  energy: 'medium',
  density: 'sparse',
  mood_tags: ['hypnotic', 'raw', 'analog'],
  swing: false,
};

const CL_BREAK: ArtistProfile = {
  genres: ['big beat', 'breakbeat', 'electronic rock'],
  bpm_range: [120, 140],
  energy: 'high',
  density: 'dense',
  mood_tags: ['punk energy', 'distorted', 'live feel'],
  swing: false,
};

export const ARTIST_MAP: Record<string, ArtistProfile> = {
  // Big room / EDM
  'david guetta': BR,
  'martin garrix': BR,
  'dimitri vegas like mike': BR,
  'dimitri vegas and like mike': BR,
  'dvlm': BR,
  'hardwell': BR,
  'afrojack': BR,
  'steve aoki': BR,
  'tiesto': BR,
  'tijs michiel verwest': BR,
  'w&w': BR,
  'willem van hanegem ward van der harst': BR,
  'timmy trumpet': BR,
  'marshmello': BR,
  'r3hab': BR,
  'blasterjaxx': BR,
  'showtek': BR,
  'deorro': BR,
  'vinai': BR,
  'nicky romero': BR,
  'dvbbs': BR,
  'kshmr': BR,
  'zedd': BR,
  'alesso': BR,
  'sebastian ingrosso': BR,
  'axwell': BR,
  'swedish house mafia': BR,
  'don diablo': { ...BR, bpm_range: [126, 132], mood_tags: ['future', 'energetic', 'mainstage'] },
  'oliver heldens': { ...BR, genres: ['future house', 'bass house'], bpm_range: [124, 130] },
  'lost frequencies': DH_MED,
  'alok': DH_MED,
  'vintage culture': DH_MED,
  'armin van buuren': TR,
  'paul van dyk': TR,
  'above beyond': TR,
  'above & beyond': TR,
  'aly fila': TR,
  'aly & fila': TR,
  'cosmic gate': TR,
  'gareth emery': TR,
  'markus schulz': TR,
  'andrew rayel': TR,
  'giuseppe ottaviani': TR,
  'ferry corsten': TR,
  'john ocallaghan': TR,
  'john o\'callaghan': TR,
  'bryan kearney': TR,
  'factor b': TR,
  'key4050': TR,
  'ilan bluestone': TR,
  'super8 tab': TR,
  'super8 & tab': TR,
  'fisher': TH,
  'fisher oz': TH,
  'john summit': TH,
  'james hype': TH,
  'dom dolla': TH,
  'chris lake': TH,
  'michael bibi': TH,
  'pawsa': TH,
  'chris stussy': TH,
  'mau p': TH,
  'wax motif': TH,
  'sidepiece': TH,
  'ac slater': TH,
  'joel corry': TH,
  'jamie jones': TH,
  'hot since 82': TH,
  'solardo': TH,
  'patrick topping': TH,
  'green velvet': TH,
  'detlef': TH,
  'lee foss': TH,
  'marc kinchen': TH,
  'anyma': MH,
  'keinemusik': MH,
  'solomun': MH,
  'tale of us': MH,
  'artbat': MH,
  'lane 8': MH,
  'ben bohmer': MH,
  'yotto': MH,
  'tinlicker': MH,
  'adriatique': MH,
  'maceo plex': MH,
  'miss monique': MH,
  'korolova': MH,
  'nora en pure': MH,
  'kolsch': MH,
  'camelphat': MH,
  'bedouin': MH,
  'whomadewho': MH,
  'black coffee': AF,
  'peggy gou': AF,
  'honey dijon': AF,
  'le twins': AF,
  'uncle waffles': AF,
  'gordo': AF,
  'carnage': AF,
  'the martinez brothers': AF,
  'ameme': AF,
  '&me': AF,
  'charlotte de witte': MT,
  'reinier zonneveld': MT_HARD,
  'amelie lens': MT,
  'indira paganotto': MT_HARD,
  'lilly palmer': MT_HARD,
  'sara landry': MT_HARD,
  'nico moreno': MT_HARD,
  'i hate models': MT_HARD,
  'adam beyer': MT,
  'ben klock': MT,
  'marcel dettmann': MT,
  'nina kraviz': MT,
  'sven vath': MT,
  'richie hawtin': MT,
  'carl cox': MT,
  'eric prydz': { ...MT, genres: ['progressive house', 'melodic techno'], density: 'normal' },
  'cirez d': { ...MT, genres: ['techno', 'dark techno'] },
  'boris brejcha': { ...MT, genres: ['minimal techno', 'high tech minimal'], mood_tags: ['quirky', 'driving', 'minimal'] },
  'paul kalkbrenner': MT,
  'stephan bodzin': MT,
  'duke dumont': DH_MED,
  'disclosure': DH_MED,
  'gorgon city': DH_MED,
  'purple disco machine': DH_MED,
  'fred again': DH_MED,
  'fred again..': DH_MED,
  'four tet': DH_MED,
  'bicep': DH_MED,
  'bonobo': { ...DH, energy: 'low' },
  'jon hopkins': { ...DH, energy: 'low', mood_tags: ['cinematic', 'ambient', 'evolving'] },
  'nicolas jaar': { ...DH, energy: 'low' },
  'dixon': DH,
  'ame': DH,
  'âme': DH,
  'folamour': { ...DH_MED, genres: ['disco house', 'french house'] },
  'flume': FB,
  'porter robinson': FB,
  'rufus du sol': FB,
  'odesza': FB,
  'illenium': FB,
  'kygo': { ...FB, genres: ['tropical house', 'pop'], bpm_range: [100, 124] },
  'robin schulz': FB,
  'felix jaehn': FB,
  'jonas blue': FB,
  'calvin harris': FB,
  'dj snake': FB,
  'galantis': FB,
  'excision': BS,
  'subtronics': BS,
  'rezz': BS,
  'skrillex': BS,
  'knife party': BS,
  'chase status': BS,
  'chase & status': BS,
  'pendulum': BS,
  'slander': BS,
  'jauz': BS,
  'rl grime': BS,
  'virtual riot': BS,
  'svdden death': BS,
  'zomboy': BS,
  'modestep': BS,
  'nero': BS,
  'flux pavilion': BS,
  'doctor p': BS,
  'spag heddy': BS,
  'daft punk': CL_EDM,
  'the chemical brothers': CL_BREAK,
  'fatboy slim': CL_BREAK,
  'underworld': CL_TECH,
  'orbital': CL_TECH,
  'the prodigy': CL_BREAK,
  'deadmau5': { ...MT, genres: ['progressive house', 'electro'], bpm_range: [126, 132] },
  'carl craig': CL_TECH,
  'jeff mills': CL_TECH,
  'laurent garnier': CL_TECH,
  'gesaffelstein': { ...MT, energy: 'high', mood_tags: ['dark', 'industrial', 'french'] },
  'john digweed': DH,
  'sasha': DH,
  'digweed': DH,
  'nic fanciulli': TH,
  'hot creations': TH,
  'paco osuna': TH,
  'joseph capriati': MT,
  'pan pot': MT,
  'bart skills': MT,
  'enrico sangiuliano': MT,
  'bartol skils': MT,
  'anna tur': MT,
  'deborah de luca': MT,
  'popof': MT,
  'worakls': MH,
  'jan blomqvist': MH,
  'monolink': MH,
  'hunter/game': MH,
  'mind against': MH,
  'stephan jolk': MH,
  'massano': MH,
  'innellea': MH,
  'colyn': MH,
  'spada': MH,
  'eli brown': TH,
  'hannah laing': TH,
  'hannah wants': TH,
  'low steppa': TH,
  'kyle watson': TH,
  'walker royce': TH,
  'claude vonstroke': TH,
  'justin martin': TH,
  'shiba san': TH,
  'malaa': TH,
  'tchami': TH,
  'mercer': TH,
  'brooks': BR,
  'quintino': BR,
  'firebeatz': BR,
  'julian jordan': BR,
  'brohug': BR,
  'mike williams': BR,
  'mesto': BR,
  'curbi': BR,
  'jay hardway': BR,
  'bassjackers': BR,
  'lucas steve': BR,
  'lucas & steve': BR,
  'matisse sadko': BR,
  'matisse & sadko': BR,
  'dubvision': BR,
  'third party': BR,
  'deniz koyu': BR,
  'fedde le grand': BR,
  'sander van doorn': TR,
  'marlo': TR,
  'marlos': TR,
  'will atkinson': TR,
  'john askew': TR,
  'astrix': TR,
  'vini vici': TR,
  'blastoyz': TR,
  'infected mushroom': TR,
  'fisher chris lake': TH,
  'ship wrek': TH,
  'valentino khan': TH,
  'tchami malaa': TH,
  'noizu': TH,
  'matroda': TH,
  'john summit tech': TH,
  'westend': TH,
  'trace amounts': TH,
  'hugel': AF,
  'kevin mccay': AF,
  'themba': AF,
  'djEFF': AF,
  'dj maphorisa': AF,
  'kabza de small': AF,
  'major league djz': AF,
  'shimza': AF,
  'black motion': AF,
  'culoe de song': AF,
  'enoo napa': AF,
  'pablo fierro': AF,
  'andhim': MH,
  'superflu': MH,
  'mees salome': MH,
  'oezlem': MH,
  'oezlem oezen': MH,
  'massano melodic': MH,
  'jimmy switch': MT_HARD,
  '999999999': MT_HARD,
  'umek': MT,
  'spektre': MT,
  'pigdan': MT,
  'layton giordani': MT,
  'wehbba': MT,
  'drunken kong': MT,
  'hannes bieger': DH,
  'atish': MH,
  'lee burridge': MH,
  'hernan cattaneo': DH,
  'nick warren': DH,
  'guy j': DH,
  'guy gerber': MH,
  'sasha digweed': DH,
  'moonwalk': MH,
  'massane': MH,
  'marsh': MH,
  'san holo': FB,
  'said the sky': FB,
  'dabin': FB,
  'seven lions': FB,
  'william black': FB,
  'crywolf': FB,
  'madeon': FB,
  'louis the child': FB,
  'whethan': FB,
  'slushii': FB,
  'nghtmre': BS,
  'sullivan king': BS,
  'kompany': BS,
  'barely alive': BS,
  'virtual self': FB,
  'pryda': { ...MT, genres: ['progressive house', 'melodic techno'] },
  'jeremy olander': { ...MT, genres: ['melodic house', 'progressive house'] },
  'tokimonsta': FB,
  'kaytranada': DH_MED,
  'the avalanches': CL_BREAK,
  'chemical brothers': CL_BREAK,
  'prodigy': CL_BREAK,
  'fat boy slim': CL_BREAK,
  'moby': CL_EDM,
  'the crystal method': CL_BREAK,
  'basement jaxx': CL_BREAK,
  'groove armada': DH_MED,
  'stardust': CL_EDM,
  'modjo': CL_EDM,
  'st germain': DH,
  'st. germain': DH,
  'mr oizo': CL_BREAK,
  'mr. oizo': CL_BREAK,
  'justice': CL_EDM,
  'sebastian tellier': DH,
  'breakbot': DH_MED,
  'chromeo': DH_MED,
  'flight facilities': FB,
  'cut copy': FB,
  'empire of the sun': FB,
  'mgmt': FB,
  'todd terje': DH_MED,
  'lindstrom': DH_MED,
  'prins thomas': DH_MED,
  'gorgon city live': DH_MED,
  'duke dumont deep': DH_MED,
  'shadow child': TH,
  'kormak': TH,
  'friend within': TH,
  'sonny fodera': TH,
  'dombresky': TH,
  'disco lines': TH,
  'disco line': TH,
  'lp giobbi': FB,
  'biig piig': FB,
  'james blake electronic': DH,
  'jamie xx': DH_MED,
  'the xx': DH_MED,
  'robyn': FB,
  'sophie': FB,
  'sophie pc music': FB,
  'ag cook': FB,
  '100 gecs': FB,
  'skrillex fred': FB,
  'aphex twin': CL_TECH,
  'squarepusher': CL_BREAK,
  'boards of canada': DH,
  'four tet remix': DH_MED,
  'nicolas jaar ambient': DH,
  'black coffee ibiza': AF,
  'keinemusik crew': MH,
  'rampa': MH,
  'adam port': MH,
  'brina krauss': MH,
  're.you': MH,
  'reyou': MH,
  'musumeci': MH,
  'dennis cruz': TH,
  'mihalis safras': TH,
  'wade': TH,
  'wade dj': TH,
  'sebjak': BR,
  'jaz von d': BR,
  'tom swoon': BR,
  'reggio': BR,
  'maor levi': BR,
  'ilan bluestone anjunabeats': TR,
  'elevven': TR,
  'oliver smith': TR,
  'sunny lax': TR,
  'dan stone': TR,
  'stoneface terminal': TR,
  'ramsterdam': TR,
  'heatbeat': TR,
  'maarten de jong': TR,
  'mark sixma': TR,
  'orjan nilsen': TR,
  'ruben de ronde': TR,
  'rodg': TR,
  'protoculture': TR,
  'protoculture trance': TR,
  'max graham': TR,
  'gareth emery lucy': TR,
  'craig connelly': TR,
  'david forbes': TR,
  'david pearce': TR,
  'factor b aussie': TR,
  'sam jones': TR,
  'sam jones trance': TR,
  'john askew VII': TR,
  'alex di stefano': TR,
  'alex morph': TR,
  'alex m.o.r.p.h.': TR,
  'heatbeat argentina': TR,
  'john o callaghan': TR,
  'will sparks': BR,
  'timmy trumpet psy': BR,
  'showtek hard': BR,
  'laidback luke': BR,
  'laidback luke miami': BR,
  'chuckie': BR,
  'sydney samson': BR,
  'sidney samson': BR,
  'afrojack remix': BR,
  'steve aoki cake': BR,
  'deorro bounce': BR,
  'vinai bounce': BR,
  'blasterjaxx maxximize': BR,
  'r3hab remix': BR,
  'kshmr ghost': BR,
  'martin garrix animals': BR,
  'martin garrix proxy': BR,
  'nicky romero toulouse': BR,
  'protocol recordings': BR,
  'armada': TR,
  'armada trance': TR,
  'anjunabeats': TR,
  'anjunadeep': MH,
  'colorize': MH,
  'enhanced': TR,
  'enhanced music': TR,
  'black hole': TR,
  'black hole recordings': TR,
  'coldharbour': TR,
  'coldharbour recordings': TR,
  'vandit': TR,
  'vandit recordings': TR,
  'cosmic gate nic': TR,
  'myon': TR,
  'shane 54': TR,
  'myon shane 54': TR,
  'gardenstate': TR,
  'gardenstate trance': TR,
  'alpha 9': TR,
  'alpha 9 arty': TR,
  'arty': TR,
  'arty trance': TR,
  'fatum': TR,
  'fatum trance': TR,
  'genix': TR,
  'genix anjunabeats': TR,
  'dt8 project': TR,
  'dt8': TR,
  'signum': TR,
  'signum trance': TR,
  'menno de jong': TR,
  'leon bolier': TR,
  'leon boiler': TR,
  'setrise': TR,
  'setrise trance': TR,
  'somna': TR,
  'somna trance': TR,
  'craig david ts5': BR,
  'david guetta show': BR,
  'afrojack vs': BR,
  'quintino bounce': BR,
  'quintino edm': BR,
  'firebeatz edm': BR,
  'julian jordan bounce': BR,
  'mike williams bounce': BR,
  'mesto bounce': BR,
  'jay hardway bounce': BR,
  'bassjackers edm': BR,
  'dubvision edm': BR,
  'third party edm': BR,
  'deniz koyu edm': BR,
  'fedde le grand edm': BR,
  'tom staar': BR,
  'tom staar edm': BR,
  'maddix': BR,
  'maddix hard': BR,
  'will sparks bounce': BR,
  'timmy trumpet bounce': BR,
  'showtek edm': BR,
  'laidback luke edm': BR,
  'chuckie edm': BR,
  'sidney samson edm': BR,
  'steve aoki edm': BR,
  'deorro edm': BR,
  'vinai edm': BR,
  'blasterjaxx edm': BR,
  'r3hab edm': BR,
  'kshmr edm': BR,
  'martin garrix edm': BR,
  'nicky romero edm': BR,
  'david guetta edm': BR,
  'martin garrix edm festival': BR,
  'afrojack edm': BR,
  'steve aoki edm festival': BR,
  'deorro edm festival': BR,
  'vinai edm festival': BR,
  'blasterjaxx edm festival': BR,
  'r3hab edm festival': BR,
  'kshmr edm festival': BR,
  'marshmello edm': BR,
  'marshmello festival': BR,
  'timmy trumpet festival': BR,
  'hardwell festival': BR,
  'hardwell edm': BR,
  'afrojack festival': BR,
  'steve aoki festival': BR,
  'deorro festival': BR,
  'vinai festival': BR,
  'blasterjaxx festival': BR,
  'r3hab festival': BR,
  'kshmr festival': BR,
  'david guetta festival': BR,
  'martin garrix festival': BR,
  'nicky romero festival': BR,
  'dvlm festival': BR,
  'dvlm edm': BR,
  'w&w festival': BR,
  'w&w edm': BR,
  'swedish house mafia edm': BR,
  'swedish house mafia festival': BR,
  'axwell festival': BR,
  'sebastian ingrosso festival': BR,
  'alesso festival': BR,
  'alesso edm': BR,
  'zedd festival': BR,
  'zedd edm': BR,
  'calvin harris festival': BR,
  'calvin harris edm': BR,
  'dj snake festival': BR,
  'dj snake edm': BR,
  'galantis festival': BR,
  'galantis edm': BR,
  'don diablo festival': BR,
  'don diablo edm': BR,
  'oliver heldens festival': BR,
  'oliver heldens edm': BR,
  'lost frequencies festival': BR,
  'lost frequencies edm': BR,
  'alok festival': BR,
  'alok edm': BR,
  'vintage culture festival': BR,
  'vintage culture edm': BR,

  // Expanded roster (aliases + additional artists)
  'alan walker': { ...BR, genres: ['melodic edm', 'electronic pop'], bpm_range: [124, 130], mood_tags: ['cinematic', 'euphoric', 'anthemic'] },
  'claptone': { ...DH_MED, genres: ['deep house', 'disco house'], mood_tags: ['golden', 'mysterious', 'groovy'], swing: false },
  'atb': { ...TR, genres: ['uplifting trance', 'vocal trance'], bpm_range: [132, 140], mood_tags: ['nostalgic', 'melodic', 'emotional'] },
  'nervo': { ...BR, genres: ['electro house', 'edm'], bpm_range: [126, 132], mood_tags: ['party', 'bouncy', 'radio'] },
  'sub zero project': { ...BR, genres: ['hardstyle', 'rawstyle'], bpm_range: [150, 165], mood_tags: ['reverse bass', 'screech', 'festival'], swing: false },
  'the chainsmokers': { ...FB, genres: ['future bass', 'pop edm'], bpm_range: [95, 128], mood_tags: ['catchy', 'emotional', 'radio'] },
  'liu': { ...BR, genres: ['big room', 'progressive house'], bpm_range: [126, 132], mood_tags: ['festival', 'driving', 'uplifting'] },
  'kaaze': { ...BR, genres: ['progressive house', 'edm'], bpm_range: [126, 132], mood_tags: ['energetic', 'melodic', 'mainstage'] },
  'burak yeter': { ...BR, genres: ['tribal house', 'edm'], bpm_range: [124, 130], mood_tags: ['percussive', 'eastern', 'club'] },
  'marnik': { ...BR, genres: ['big room', 'electro house'], bpm_range: [126, 132], mood_tags: ['bounce', 'euphoric', 'festival'] },
  'wukong': { ...BR, genres: ['hard dance', 'big room'], bpm_range: [150, 160], mood_tags: ['intense', 'oriental', 'drop'], swing: false },
  'plastik funk': { ...BR, genres: ['future house', 'bass house'], bpm_range: [124, 128], mood_tags: ['funky', 'bouncy', 'club'] },
  'cuebrick': { ...BR, genres: ['future house', 'edm'], bpm_range: [126, 130], mood_tags: ['bright', 'energetic', 'festival'] },
  'mariana bo': { ...TR, genres: ['psy trance', 'progressive psy'], bpm_range: [138, 145], mood_tags: ['tribal', 'hypnotic', 'festival'] },
  'meduza': { ...DH_MED, genres: ['deep house', 'slap house'], bpm_range: [122, 126], mood_tags: ['dark', 'minimal', 'groovy'] },
  'fantasm': { ...BR, genres: ['future house', 'electro'], bpm_range: [124, 130], mood_tags: ['quirky', 'energetic', 'club'] },
  'faustix': { ...BR, genres: ['future bass', 'edm'], bpm_range: [124, 128], mood_tags: ['anthemic', 'bright', 'pop'] },
  'nils van zandt': { ...DH_MED, genres: ['slap house', 'bass house'], bpm_range: [122, 126], mood_tags: ['bouncy', 'minimal', 'club'] },
  'topic': { ...DH_MED, genres: ['deep house', 'dance pop'], bpm_range: [120, 124], mood_tags: ['smooth', 'radio', 'melodic'] },
  'marlon hoffstadt': { ...BR, genres: ['euro dance', 'hyper techno'], bpm_range: [145, 155], mood_tags: ['fast', 'euphoric', 'rave'], swing: false },
  'pete tong': { ...MH, genres: ['progressive house', 'melodic house'], bpm_range: [122, 128], mood_tags: ['sophisticated', 'warm', 'club'] },
  'danny tenaglia': { ...TH, genres: ['tribal house', 'progressive house'], bpm_range: [124, 130], mood_tags: ['tribal', 'driving', 'hypnotic'], swing: true },
  'gryffin': { ...FB, genres: ['future bass', 'melodic dubstep'], bpm_range: [88, 118], mood_tags: ['emotional', 'uplifting', 'cinematic'] },
  'dillon francis': { ...BS, genres: ['moombahton', 'trap', 'bass house'], bpm_range: [128, 150], mood_tags: ['party', 'quirky', 'heavy'], swing: false },
  'snakehips': { ...DH_MED, genres: ['rnb', 'future bass'], bpm_range: [95, 110], mood_tags: ['smooth', 'soulful', 'late night'] },
  'vicetone': { ...BR, genres: ['progressive house', 'edm'], bpm_range: [126, 132], mood_tags: ['melodic', 'euphoric', 'anthemic'] },
  'sick individuals': { ...BR, genres: ['big room', 'electro house'], bpm_range: [126, 132], mood_tags: ['energetic', 'mainstage', 'driving'] },
  'dada life': { ...BR, genres: ['big room', 'electro house'], bpm_range: [128, 134], mood_tags: ['chaotic', 'euphoric', 'bananas'] },
  'kaskade': { ...MH, genres: ['progressive house', 'vocal house'], bpm_range: [122, 128], mood_tags: ['emotional', 'uplifting', 'warm'] },
  'benny benassi': { ...BR, genres: ['electro house', 'italo dance'], bpm_range: [126, 132], mood_tags: ['saturated', 'club', 'classic'] },
  'dimitri vangelis and wyman': { ...BR, genres: ['progressive house', 'edm'], bpm_range: [126, 130], mood_tags: ['melodic', 'anthemic', 'festival'] },
  'dimitri vangelis & wyman': { ...BR, genres: ['progressive house', 'edm'], bpm_range: [126, 130], mood_tags: ['melodic', 'anthemic', 'festival'] },
  'ricardo villalobos': { ...TH, genres: ['minimal house', 'microhouse'], bpm_range: [124, 128], energy: 'low', density: 'sparse', mood_tags: ['minimal', 'hypnotic', 'subtle'], swing: true },
  'seth troxler': { ...TH, genres: ['tech house', 'minimal techno'], bpm_range: [124, 130], mood_tags: ['weird', 'freaky', 'grooving'], swing: true },
  'the blessed madonna': { ...DH_MED, genres: ['disco house', 'classic house'], bpm_range: [118, 124], mood_tags: ['soulful', 'disco', 'uplifting'], swing: false },
  'mark knight': { ...TH, genres: ['tech house', 'funky house'], bpm_range: [124, 128], mood_tags: ['funky', 'driving', 'club'], swing: true },
  'mk': TH,
  'zeds dead': { ...BS, genres: ['dubstep', 'bass music'], bpm_range: [140, 150], mood_tags: ['heavy', 'dark', 'wobble'] },
  'alison wonderland': { ...FB, genres: ['future bass', 'trap'], bpm_range: [140, 160], mood_tags: ['emotional', 'aggressive', 'anthemic'] },
  'andy c': { ...BS, genres: ['drum and bass', 'jungle'], bpm_range: [174, 180], mood_tags: ['rolling', 'dancefloor', 'energetic'] },
  'kill the noise': { ...BS, genres: ['dubstep', 'electro house'], bpm_range: [140, 150], mood_tags: ['chaotic', 'heavy', 'distorted'] },
  'baauer': { ...BS, genres: ['trap', 'bass music'], bpm_range: [140, 150], mood_tags: ['hiphop', 'hard', 'club'] },
  'flosstradamus': { ...BS, genres: ['trap', 'festival trap'], bpm_range: [140, 150], mood_tags: ['hype', '808', 'party'] },
  'troyboi': { ...BS, genres: ['trap', 'future beats'], bpm_range: [130, 145], mood_tags: ['dark', 'bouncy', 'uk'] },
  'moderat': { ...MH, genres: ['electronic', 'indietronica'], bpm_range: [110, 122], energy: 'medium', mood_tags: ['cinematic', 'melancholic', 'synth'] },
  'zhu': { ...MH, genres: ['deep house', 'electronic pop'], bpm_range: [118, 124], mood_tags: ['mysterious', 'nocturnal', 'smooth'] },
  'bob sinclar': { ...DH_MED, genres: ['french house', 'disco house'], bpm_range: [122, 126], mood_tags: ['disco', 'groovy', 'summer'] },
  'martin solveig': { ...DH_MED, genres: ['french house', 'dance pop'], bpm_range: [122, 126], mood_tags: ['funky', 'radio', 'bright'] },
  'kungs': { ...DH_MED, genres: ['future house', 'deep house'], bpm_range: [122, 126], mood_tags: ['funky', 'groovy', 'radio'] },
  'sigala': { ...FB, genres: ['dance pop', 'house'], bpm_range: [105, 122], mood_tags: ['uplifting', 'horns', 'party'] },
  'jax jones': { ...DH_MED, genres: ['house', 'dance pop'], bpm_range: [120, 126], mood_tags: ['bouncy', 'radio', 'club'] },
  'mall grab': { ...DH, genres: ['lo-fi house', 'outsider house'], bpm_range: [124, 130], energy: 'medium', mood_tags: ['lo-fi', 'raw', 'dusty'], swing: false },
  'skin on skin': { ...MT_HARD, genres: ['hard techno', 'industrial'], bpm_range: [145, 152], mood_tags: ['raw', 'relentless', 'peak'] },
  'sammy virji': { ...TH, genres: ['uk garage', 'bassline'], bpm_range: [132, 138], mood_tags: ['bouncy', '2-step', 'vocal'], swing: true },
  'interplanetary criminal': { ...TH, genres: ['uk garage', 'bassline'], bpm_range: [132, 138], mood_tags: ['nostalgic', 'bouncy', 'street'] },
  'diplo': { ...BR, genres: ['moombahton', 'dancehall', 'edm'], bpm_range: [100, 128], mood_tags: ['global', 'party', 'club'] },
  'major lazer': { ...BR, genres: ['dancehall', 'edm', 'moombahton'], bpm_range: [100, 128], mood_tags: ['tropical', 'party', 'bass'] },
  'ofenbach': { ...DH_MED, genres: ['french house', 'deep house'], bpm_range: [120, 124], mood_tags: ['groovy', 'radio', 'summer'] },
  'a-trak': { ...TH, genres: ['house', 'hiphop crossover'], bpm_range: [124, 128], mood_tags: ['turntablist', 'funky', 'club'], swing: true },
  'boys noize': { ...MT_HARD, genres: ['electro', 'industrial techno'], bpm_range: [128, 138], mood_tags: ['distorted', 'punk', 'rave'] },
  'ellen allien': { ...MT, genres: ['techno', 'experimental'], bpm_range: [128, 135], mood_tags: ['quirky', 'berlin', 'hypnotic'] },
  'monika kruse': { ...MT, genres: ['techno', 'peak techno'], bpm_range: [130, 136], mood_tags: ['driving', 'hypnotic', 'club'] },
  'nicole moudaber': { ...MT, genres: ['techno', 'dark techno'], bpm_range: [128, 132], mood_tags: ['dark', 'rolling', 'hypnotic'] },
  'chris liebing': { ...MT_HARD, genres: ['industrial techno', 'techno'], bpm_range: [135, 142], mood_tags: ['raw', 'driving', 'minimal'] },
  'len faki': { ...MT, genres: ['techno', 'peak techno'], bpm_range: [132, 138], mood_tags: ['berghain', 'driving', 'hypnotic'] },
  'dj seinfeld': { ...DH, genres: ['lo-fi house', 'outsider house'], bpm_range: [118, 124], energy: 'low', mood_tags: ['lo-fi', 'nostalgic', 'tape'] },
  'overmono': { ...TH, genres: ['uk garage', 'breakbeat'], bpm_range: [132, 140], mood_tags: ['vocal chops', 'uk', 'future'] },
  'ross from friends': { ...MH, genres: ['lo-fi house', 'electronica'], bpm_range: [118, 124], mood_tags: ['dreamy', 'lo-fi', 'live'] },
  'mount kimbie': { ...DH_MED, genres: ['post dubstep', 'electronica'], bpm_range: [130, 140], mood_tags: ['textural', 'melodic', 'experimental'] },
  'caribou': { ...DH_MED, genres: ['indie electronic', 'downtempo'], bpm_range: [110, 124], mood_tags: ['organic', 'dreamy', 'live'] },
  'floating points': { ...DH_MED, genres: ['deep house', 'electronic jazz'], bpm_range: [118, 126], mood_tags: ['sophisticated', 'warm', 'live'] },
  'blond:ish': { ...MH, genres: ['melodic house', 'organic house'], bpm_range: [118, 124], mood_tags: ['spiritual', 'tribal', 'warm'], swing: true },
  'blondish': { ...MH, genres: ['melodic house', 'organic house'], bpm_range: [118, 124], mood_tags: ['spiritual', 'tribal', 'warm'], swing: true },
  'cassian': { ...MH, genres: ['melodic house', 'progressive house'], bpm_range: [120, 126], mood_tags: ['emotional', 'warm', 'driving'] },
  'argy': { ...MH, genres: ['melodic techno', 'indie dance'], bpm_range: [122, 128], mood_tags: ['vocal', 'euphoric', 'peak'] },
  'matt sassari': { ...TH, genres: ['tech house', 'peak tech'], bpm_range: [126, 132], mood_tags: ['driving', 'percussive', 'club'], swing: true },
  'ki/ki': { ...MT_HARD, genres: ['acid techno', 'hard trance'], bpm_range: [145, 155], mood_tags: ['acid', 'fast', 'rave'], swing: false },
  'horsegiirl': { ...MT_HARD, genres: ['hard dance', 'eurodance'], bpm_range: [150, 165], mood_tags: ['playful', 'speed', 'meme'], swing: false },
  'nia archives': { ...BS, genres: ['jungle', 'drum and bass'], bpm_range: [168, 174], mood_tags: ['soulful', 'uk', 'rolling'] },
  'knock2': { ...BS, genres: ['bass house', 'trap'], bpm_range: [130, 148], mood_tags: ['hype', 'festival', 'bounce'] },
  'isoxo': { ...BS, genres: ['wave', 'trap', 'experimental bass'], bpm_range: [140, 155], mood_tags: ['chaotic', 'sound design', 'dark'] },
  'hamdi': { ...BS, genres: ['uk dubstep', '140 bass'], bpm_range: [138, 145], mood_tags: ['grimey', 'weighty', 'uk'] },
  'max styler': { ...TH, genres: ['tech house', 'progressive house'], bpm_range: [124, 130], mood_tags: ['melodic', 'driving', 'club'] },
  'odd mob': { ...TH, genres: ['tech house', 'bass house'], bpm_range: [124, 128], mood_tags: ['bouncy', 'funky', 'peak'] },
  'the sponges': { ...DH_MED, genres: ['disco house', 'funk house'], bpm_range: [118, 124], mood_tags: ['funky', 'disco', 'groovy'], swing: true },
  'drezo': { ...TH, genres: ['g-house', 'dark house'], bpm_range: [124, 128], mood_tags: ['dark', 'minimal', 'groovy'] },
  'griz': { ...FB, genres: ['future funk', 'livetronica'], bpm_range: [95, 115], mood_tags: ['sax', 'funk', 'soulful'] },
  'lsdream': { ...BS, genres: ['psybass', 'midtempo bass'], bpm_range: [85, 110], mood_tags: ['psychedelic', 'dreamy', 'wub'] },
  'ganja white night': { ...BS, genres: ['dubstep', 'riddim'], bpm_range: [140, 150], mood_tags: ['wobble', 'heavy', 'stoner'] },
  'boogie t': { ...BS, genres: ['swamp bass', 'dubstep'], bpm_range: [135, 145], mood_tags: ['funky', 'grimy', 'bounce'] },
  'clozee': { ...FB, genres: ['world bass', 'melodic bass'], bpm_range: [90, 115], mood_tags: ['organic', 'tribal', 'cinematic'] },
  'tycho': { ...DH, genres: ['ambient', 'downtempo'], bpm_range: [85, 100], energy: 'low', density: 'sparse', mood_tags: ['ambient', 'shoegaze', 'warm'] },
  'emancipator': { ...DH, genres: ['downtempo', 'trip hop'], bpm_range: [85, 100], energy: 'low', density: 'sparse', mood_tags: ['organic', 'melodic', 'chill'] },
  'pretty lights': { ...DH_MED, genres: ['livetronica', 'glitch hop'], bpm_range: [95, 110], mood_tags: ['soulful', 'festival', 'groovy'] },
  'big gigantic': { ...FB, genres: ['livetronica', 'future funk'], bpm_range: [100, 118], mood_tags: ['sax', 'bouncy', 'festival'] },
  'thievery corporation': { ...DH, genres: ['downtempo', 'trip hop'], bpm_range: [90, 105], energy: 'low', mood_tags: ['lounge', 'dub', 'global'] },
  'noisia': { ...BS, genres: ['neurofunk', 'drum and bass'], bpm_range: [172, 178], mood_tags: ['technical', 'dark', 'rolling'] },
  'camo and krooked': { ...BS, genres: ['drum and bass', 'liquid'], bpm_range: [174, 180], mood_tags: ['melodic', 'polished', 'rolling'] },
  'camo & krooked': { ...BS, genres: ['drum and bass', 'liquid'], bpm_range: [174, 180], mood_tags: ['melodic', 'polished', 'rolling'] },
  'dimension': { ...BS, genres: ['drum and bass', 'dancefloor dnb'], bpm_range: [174, 178], mood_tags: ['anthemic', 'energetic', 'rolling'] },
  'wilkinson': { ...BS, genres: ['liquid drum and bass'], bpm_range: [174, 180], mood_tags: ['soulful', 'melodic', 'rolling'] },
  'sub focus': { ...BS, genres: ['drum and bass', 'electronic'], bpm_range: [174, 178], mood_tags: ['anthemic', 'energetic', 'cinematic'] },
  'sigma': { ...BS, genres: ['drum and bass', 'crossover'], bpm_range: [168, 176], mood_tags: ['vocal', 'chart', 'rolling'] },
  'netsky': { ...BS, genres: ['liquid drum and bass'], bpm_range: [174, 180], mood_tags: ['liquid', 'euphoric', 'melodic'] },
  'friction': { ...BS, genres: ['drum and bass', 'techstep'], bpm_range: [172, 178], mood_tags: ['dark', 'technical', 'rolling'] },
  'goldie': { ...BS, genres: ['jungle', 'drum and bass'], bpm_range: [160, 170], mood_tags: ['atmospheric', 'amen', 'classic'] },
  'ltj bukem': { ...BS, genres: ['atmospheric drum and bass', 'intelligent'], bpm_range: [168, 174], energy: 'medium', density: 'normal', mood_tags: ['atmospheric', 'jazzy', 'deep'] },
  'black sun empire': { ...BS, genres: ['neurofunk', 'dark drum and bass'], bpm_range: [172, 178], mood_tags: ['dark', 'sci-fi', 'technical'] },
  'wata igarashi': { ...MT, genres: ['hypnotic techno', 'dub techno'], bpm_range: [128, 134], density: 'sparse', mood_tags: ['hypnotic', 'dub', 'minimal'] },
  'batu': { ...MT, genres: ['uk techno', 'bass techno'], bpm_range: [130, 138], mood_tags: ['percussive', 'uk', 'weighty'] },
  'polygonia': { ...MT, genres: ['ambient techno', 'experimental'], bpm_range: [120, 128], energy: 'low', density: 'sparse', mood_tags: ['organic', 'textural', 'dreamy'] },
  'verraco': { ...MT_HARD, genres: ['industrial techno', 'experimental'], bpm_range: [138, 148], mood_tags: ['raw', 'distorted', 'club'] },
  'carlita': { ...MH, genres: ['melodic house', 'tribal house'], bpm_range: [118, 124], mood_tags: ['warm', 'percussive', 'sunset'], swing: true },
  'avicii': { ...BR, genres: ['progressive house', 'edm'], bpm_range: [126, 132], mood_tags: ['euphoric', 'melodic', 'anthemic'] },
  'mochakk': { ...TH, genres: ['tech house', 'latin house'], bpm_range: [126, 132], mood_tags: ['percussive', 'funky', 'peak'], swing: true },
  'spencer brown': { ...TR, genres: ['progressive trance', 'melodic trance'], bpm_range: [128, 136], mood_tags: ['melodic', 'emotional', 'driving'] },
};

function normalizeInnerSpaces(s: string): string {
  return s.replace(/\s+/g, ' ').trim();
}

/** Word-boundary style: padded spaces so substrings of words do not match. */
export function findArtistKeyInNormalizedPrompt(normPrompt: string): string | null {
  const padded = ` ${normalizeInnerSpaces(normPrompt)} `;
  const keys = Object.keys(ARTIST_MAP).sort((a, b) => b.length - a.length);
  for (const key of keys) {
    const needle = ` ${normalizeInnerSpaces(key)} `;
    if (padded.includes(needle)) return key;
  }
  return null;
}

/**
 * Resolve a string (prompt fragment or full prompt) to a profile: exact key,
 * then longest substring match in normalized space.
 */
export function resolveArtistToParams(input: string): ArtistProfile | null {
  const norm = normalizeArtistKey(input);
  if (!norm) return null;
  if (ARTIST_MAP[norm]) return ARTIST_MAP[norm];
  const key = findArtistKeyInNormalizedPrompt(norm);
  if (key) return ARTIST_MAP[key];
  return null;
}

export function findArtistInPrompt(prompt: string): { matchedKey: string; profile: ArtistProfile } | null {
  const norm = normalizeArtistKey(prompt);
  const key = findArtistKeyInNormalizedPrompt(norm);
  if (!key) return null;
  return { matchedKey: key, profile: ARTIST_MAP[key]! };
}
