import Link from 'next/link';

function Card({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div
      className="rounded-2xl p-5"
      style={{
        background: 'var(--surface)',
        border: '1px solid var(--border)',
      }}
    >
      <div style={{ fontFamily: 'Syne, sans-serif', fontWeight: 800, fontSize: 18, color: 'var(--text)' }}>
        {title}
      </div>
      <div className="mt-3" style={{ color: 'var(--muted)', lineHeight: 1.8 }}>
        {children}
      </div>
    </div>
  );
}

export default function LicensePage() {
  return (
    <div className="min-h-screen px-6 py-16" style={{ background: 'var(--bg)', color: 'var(--text)' }}>
      <div className="mx-auto" style={{ maxWidth: 720 }}>
        <Link href="/" style={{ textDecoration: 'none', color: 'var(--accent)', fontFamily: 'JetBrains Mono, monospace', fontSize: 12 }}>
          ← Back to pulp
        </Link>

        <h1 className="mt-6" style={{ fontFamily: 'Syne, sans-serif', fontWeight: 800, fontSize: 34, letterSpacing: '-0.02em' }}>
          Commercial License
        </h1>
        <p className="mt-3" style={{ color: 'var(--muted)' }}>
          A clear summary of how you can use the MIDI generated by pulp.
        </p>

        <div className="mt-8 grid grid-cols-1 gap-4">
          <Card title="Free plan">
            <ul style={{ paddingLeft: 18 }}>
              <li className="mt-2">Personal use only.</li>
              <li className="mt-2">Non-commercial projects only.</li>
              <li className="mt-2">Attribution appreciated (e.g. “made with pulp”).</li>
            </ul>
          </Card>

          <Card title="Pro plan">
            <ul style={{ paddingLeft: 18 }}>
              <li className="mt-2">Full commercial rights.</li>
              <li className="mt-2">Royalty-free usage.</li>
              <li className="mt-2">No attribution required.</li>
            </ul>
          </Card>

          <Card title="Royalty-free + ownership">
            <p>
              All MIDI generated by pulp is intended to be original and royalty-free. pulp does not claim copyright in your
              generations. You own the MIDI you generate, subject to the plan terms above.
            </p>
          </Card>

          <Card title="No copyright claims from pulp">
            <p>
              pulp will not assert copyright claims over your generated MIDI. You are responsible for how you use the MIDI
              and for complying with applicable laws and third-party terms (e.g. distribution platforms).
            </p>
          </Card>
        </div>

        <div className="mt-12 pt-6" style={{ borderTop: '1px solid var(--border)', color: 'color-mix(in srgb, var(--muted) 75%, transparent)' }}>
          <p style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 12 }}>
            Last updated: 2026-04-08
          </p>
        </div>
      </div>
    </div>
  );
}

